include: package:very_good_analysis/analysis_options.2.4.0.yaml

linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: false

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
  errors:
    invalid_annotation_target: ignore
