name: calc
description: Calculator App.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.4
  freezed_annotation: ^2.0.3

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
